export declare const SECONDS_A_MINUTE = 60;
export declare const SECONDS_A_HOUR: number;
export declare const SECONDS_A_DAY: number;
export declare const SECONDS_A_WEEK: number;
export declare const MILLISECONDS_A_SECOND = 1000;
export declare const MILLISECONDS_A_MINUTE: number;
export declare const MILLISECONDS_A_HOUR: number;
export declare const MILLISECONDS_A_DAY: number;
export declare const MILLISECONDS_A_WEEK: number;
export declare const INVALID_DATE_STRING = "Invalid Date";
export declare const DEFAULT_FORMAT = "YYYY-MM-DDTHH:mm:ssZ";
export declare const REGEX_PARSE: RegExp;
export declare const REGEX_FORMAT: RegExp;
export declare const UNIT_YEAR = "year";
export declare const UNIT_MONTH = "month";
export declare const UNIT_QUARTER = "quarter";
export declare const UNIT_WEEK = "week";
export declare const UNIT_DAY = "day";
export declare const UNIT_DATE = "date";
export declare const UNIT_HOUR = "hour";
export declare const UNIT_MINUTE = "minute";
export declare const UNIT_SECOND = "second";
export declare const UNIT_MILLISECOND = "millisecond";
export declare const GETTER_SETTER_METHODS: {
    readonly year: "FullYear";
    readonly month: "Month";
    readonly date: "Date";
    readonly day: "Day";
    readonly hour: "Hours";
    readonly minute: "Minutes";
    readonly second: "Seconds";
    readonly millisecond: "Milliseconds";
};
